version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: internship_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: internship_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: internship_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/internship_db
      SECRET_KEY: your_super_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
